### ISSUE TITLE
Command args obscured with base-16 encoding

### ISSUE THREAD

**Issue by NathanBaulch** [go-redis/redisext#20]
I often store small JSON objects in Redis but `redisext.OpenTelemetryHook` hides these values because they typically contain `"{},` characters. Perhaps `isSimpleByte` could be made configurable somehow? I also have some data that contains `=` which I wouldn't mind seeing in my traces. Personally, I'm fine with allowing any bytes between 0x21 and 0x7E inclusive.

**Comment by vmihailenco** [comment]
Makes sense - closed by https://github.com/go-redis/redisext/commit/57944d3c4cd12c30c2ff0037e2e23af01970b6bd
