### ISSUE TITLE
Do we need limit max cmd length?

### ISSUE THREAD

**Issue by j2gg0s** [go-redis/redisext#7]
We only limit max args length in ``otel.go:119``

**Comment by vmihailenco** [comment]
Not sure. What problem do you try to solve?

**Comment by j2gg0s** [comment]
@vmihailenco No, I just afraid of the label "redis.cmd" has too much context.

**Comment by vmihailenco** [comment]
@j2gg0s could you share the problematic cmd and how it is supposed to look like?

**Comment by j2gg0s** [comment]
@vmihailenco sorry to reply you so late.

Somebody used mget with more than thousands key, and make span is too large.
It's not right and rarely, so may be we don't need to check and limit lenght of "redis.cmd"

**Comment by vmihailenco** [comment]
Thanks, I've added the limit on number of args in a command in v0.2.0
